#!/bin/bash
set -e

docker build --build-arg BASE_IMAGE=blackpeardigital/php-nginx:7.4 -t $DOCKER_REPO:$DOCKER_TAG .
docker build --build-arg BASE_IMAGE=blackpeardigital/php-nginx:7.4-dev -t $DOCKER_REPO:$DOCKER_TAG-dev .
