#!/bin/bash
set -e

if [ "$DOCKER_TAG" == "latest" ] ; then 
    docker build --build-arg BASE_IMAGE=blackpeardigital/php-nginx:latest -t $DOCKER_REPO:latest .
    docker build --build-arg BASE_IMAGE=blackpeardigital/php-nginx:dev -t $DOCKER_REPO:dev .

    docker build --build-arg BASE_IMAGE=blackpeardigital/php-nginx:7.3 -t $DOCKER_REPO:7.3 .
    docker build --build-arg BASE_IMAGE=blackpeardigital/php-nginx:7.3-dev -t $DOCKER_REPO:7.3-dev .

    docker build --build-arg BASE_IMAGE=blackpeardigital/php-nginx:7.4 -t $DOCKER_REPO:7.4 .
    docker build --build-arg BASE_IMAGE=blackpeardigital/php-nginx:7.4-dev -t $DOCKER_REPO:7.4-dev .
else
    docker build --build-arg BASE_IMAGE=blackpeardigital/php-nginx:7.3 -t $DOCKER_REPO:$DOCKER_TAG .
    docker build --build-arg BASE_IMAGE=blackpeardigital/php-nginx:7.3-dev -t $DOCKER_REPO:$DOCKER_TAG-dev .

    docker build --build-arg BASE_IMAGE=blackpeardigital/php-nginx:7.3 -t $DOCKER_REPO:$DOCKER_TAG-7.3 .
    docker build --build-arg BASE_IMAGE=blackpeardigital/php-nginx:7.3-dev -t $DOCKER_REPO:$DOCKER_TAG-7.3-dev .

    docker build --build-arg BASE_IMAGE=blackpeardigital/php-nginx:7.4 -t $DOCKER_REPO:$DOCKER_TAG-7.4 .
    docker build --build-arg BASE_IMAGE=blackpeardigital/php-nginx:7.4-dev -t $DOCKER_REPO:$DOCKER_TAG-7.4-dev .
fi

