#!/bin/bash
if [ "$DOCKER_TAG" == "latest" ] ; then 
    docker push $DOCKER_REPO:latest
    docker push $DOCKER_REPO:dev

    docker push $DOCKER_REPO:7.3
    docker push $DOCKER_REPO:7.3-dev

    docker push $DOCKER_REPO:7.4
    docker push $DOCKER_REPO:7.4-dev
else
    docker push $DOCKER_REPO:$DOCKER_TAG
    docker push $DOCKER_REPO:$DOCKER_TAG-dev

    docker push $DOCKER_REPO:$DOCKER_TAG-7.3
    docker push $DOCKER_REPO:$DOCKER_TAG-7.3-dev

    docker push $DOCKER_REPO:$DOCKER_TAG-7.4
    docker push $DOCKER_REPO:$DOCKER_TAG-7.4-dev
fi

