name: Check WordPress Version & Tag

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch: {}  # Optional: allows manual trigger

jobs:
  check_wp:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository with full history
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Needed to check existing tags and push new ones

      - name: Get Latest WordPress Version
        id: wp_version
        run: |
          # Query the WordPress core API to get the current version
          WP_LATEST=$(curl -s https://api.wordpress.org/core/version-check/1.7/ | jq -r '.offers[0].current')
          echo "Latest WordPress version is $WP_LATEST"
          echo "::set-output name=version::$WP_LATEST"

      - name: Check if Git Tag Exists
        id: check_tag
        run: |
          TAG="${{ steps.wp_version.outputs.version }}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists."
            echo "::set-output name=tag_exists::true"
          else
            echo "Tag $TAG does not exist."
            echo "::set-output name=tag_exists::false"
          fi

      - name: Create and Push Git Tag
        if: steps.check_tag.outputs.tag_exists == 'false'
        run: |
          TAG="${{ steps.wp_version.outputs.version }}"
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git tag -a "$TAG" -m "Release WordPress version $TAG"
          git push origin "$TAG"
